In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('uttar_pradesh_grievances_dataset_updated.csv')
df.head()

,Grievance ID,Name,Contact,Email,Description,Submission Date,Department,Category,Priority,Sentiment,Location,Status,Resolution Date,Resolution Time (days),Feedback
0,G-00001,Shalini Tiwari,8626684731,user0@example.com,"Violence in certain areas has escalated, with ...",2022-08-31,Municipality,Environment,High,Negative,Ghaziabad,Resolved,2022-09-14,14.0,5.0
1,G-00002,Neha Singh,7825435601,user1@example.com,"Garbage is not being collected regularly, lead...",2022-09-05,Education,Education,Medium,Positive,Kanpur,Pending,NaN,NaN,NaN
2,G-00003,Neha Singh,8284931938,user2@example.com,"Violence in certain areas has escalated, with ...",2022-06-03,Police,Healthcare,Medium,Positive,Varanasi,Resolved,2022-06-16,13.0,4.0
3,G-00004,Vikram Rathore,9248883589,user3@example.com,Road accidents have increased due to lack of p...,2022-05-19,Transport,Public Safety,Low,Positive,Meerut,In Progress,NaN,NaN,NaN
4,G-00005,Vikram Rathore,7314108674,user4@example.com,"Roads in the area are severely damaged, causin...",2022-10-10,Health,Infrastructure,Critical,Neutral,Aligarh,Pending,NaN,NaN,NaN

In [5]:
df.isnull()

,Grievance ID,Name,Contact,Email,Description,Submission Date,Department,Category,Priority,Sentiment,Location,Status,Resolution Date,Resolution Time (days),Feedback
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4996,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4997,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4998,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
4999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().any(axis=0)

Grievance ID              False
Name                      False
Contact                   False
Email                     False
Description               False
Submission Date           False
Department                False
Category                  False
Priority                  False
Sentiment                 False
Location                  False
Status                    False
Resolution Date            True
Resolution Time (days)     True
Feedback                   True
dtype: bool

In [9]:
df.drop(columns = ['Resolution Date', 'Resolution Time (days)' , 'Feedback'], inplace = True)

In [10]:
df.head()

,Grievance ID,Name,Contact,Email,Description,Submission Date,Department,Category,Priority,Sentiment,Location,Status
0,G-00001,Shalini Tiwari,8626684731,user0@example.com,"Violence in certain areas has escalated, with ...",2022-08-31,Municipality,Environment,High,Negative,Ghaziabad,Resolved
1,G-00002,Neha Singh,7825435601,user1@example.com,"Garbage is not being collected regularly, lead...",2022-09-05,Education,Education,Medium,Positive,Kanpur,Pending
2,G-00003,Neha Singh,8284931938,user2@example.com,"Violence in certain areas has escalated, with ...",2022-06-03,Police,Healthcare,Medium,Positive,Varanasi,Resolved
3,G-00004,Vikram Rathore,9248883589,user3@example.com,Road accidents have increased due to lack of p...,2022-05-19,Transport,Public Safety,Low,Positive,Meerut,In Progress
4,G-00005,Vikram Rathore,7314108674,user4@example.com,"Roads in the area are severely damaged, causin...",2022-10-10,Health,Infrastructure,Critical,Neutral,Aligarh,Pending

In [12]:
df.drop(columns=['Grievance ID', 'Name', 'Contact', 'Email', 'Submission Date', 
                 'Department', 'Category', 'Priority', 'Sentiment', 
                 'Location', 'Status'], inplace=True)

In [13]:
df.head()

                                         Description
0  Violence in certain areas has escalated, with ...
1  Garbage is not being collected regularly, lead...
2  Violence in certain areas has escalated, with ...
3  Road accidents have increased due to lack of p...
4  Roads in the area are severely damaged, causin...

In [14]:
df.to_csv('cleaned_uttar_pradesh_grievances_dataset_updated.csv', index=False)